### ISSUE TITLE
Wrong time

### ISSUE THREAD

**Issue by Mykola2** [hmlON/room538#11]
![image](https://cloud.githubusercontent.com/assets/5686122/25899029/f07ad88e-3596-11e7-960c-59b64f05fa2c.png)

Must be 11:54 UTC+3

**Comment by hmlON** [comment]
Time is correct.
It's just in UTC timezone.

**Comment by Mykola2** [comment]
I`m not familiar with time zone concept. I live in Ukraine and its wrong time for me.
